on: push
name: Build and release on push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: artemShelest/github-action-ghr@zip
        env:
          GHR_ARCH_NAME: ./vertex_rig.zip
          GHR_PATH: ./vertex_rig/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
