on: push
name: Upload artifact on push
jobs:
  release:
    name: Release Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: zip -r vertex_rig.zip . -i ./vertex_rig/*
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        uses: artemShelest/github-action-ghr@zip
        env:
          GHR_ARCH_NAME: vertex_rig.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
